In [1]:
!git clone https://github.com/OdincovMD/img2txt.git

Cloning into 'img2txt'...
remote: Enumerating objects: 643, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (95/95), done.
remote: Total 643 (delta 30), reused 91 (delta 14), pack-reused 530 (from 1)
Receiving objects: 100% (643/643), 12.30 MiB | 22.53 MiB/s, done.
Resolving deltas: 100% (277/277), done.

In [2]:
import sys
from pathlib import Path

img2txt_path = Path("/kaggle/working/img2txt")
sys.path.insert(0, str(img2txt_path))

In [3]:
!pip install python-resize-image -q
!pip install ultralytics -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 19.9 MB/s eta 0:00:00a 0:00:01

In [4]:
import pandas as pd
from extraction.feature_extraction_batch import extract_features_batch, images_to_df
from analysis.distribution_analysis import main as analysis
from bucketing.feature_bucketing_batch import bucket_features_batch
from model.run import xgb
from model.mlp_optuna import mlp
from model.mlp_run import mlp_run


# Пути
IMAGE_DIR = "/kaggle/input/datasets/mihailodin1/all-image-skin"
YOLO_WEIGHTS = "/kaggle/input/datasets/mihailodin1/skinweightalllast-version/weight/mask_builder_yolo.pt"
UNET_WEIGHTS = "/kaggle/input/datasets/mihailodin1/skinweightalllast-version/weight/mask_builder_unet.pth"
FEATURES_CSV = "/kaggle/working/img2txt/bucketed_features.csv"
ANNOTATIONS_CSV = "/kaggle/working/img2txt/annotations.csv"

Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.

In [5]:
from extraction.segmentation import  main

In [9]:
from PIL import Image
import numpy as np

mask = main(
    "/kaggle/input/datasets/mihailodin1/all-image-skin/100.jpg",
    YOLO_WEIGHTS, 
    UNET_WEIGHTS
)

mask_img = Image.fromarray(mask)
mask_img.save("100_mask.jpg")

## Шаг 1. Извлечение описательных статистик.

### 1.1 Разметка набора изображений.

In [5]:
# df = images_to_df(IMAGE_DIR)
# df = extract_features_batch(df, yolo_weights=YOLO_WEIGHTS, unet_weights=UNET_WEIGHTS)
# df.to_csv(FEATURES_CSV, index=False)
# print(f"Извлечено: {len(df)} изображений, успешно: {(df['status'] == 'success').sum()}")

### 1.2 Загрузка готовой разметки.

In [6]:
df = pd.read_csv(FEATURES_CSV)

In [7]:
df.head(2)

,image_path,status,mean_H_lesion,mean_S_lesion,mean_V_lesion,std_H_lesion,std_S_lesion,std_V_lesion,color_balance_B,color_balance_G,...,bucket_lbp_entropy,bucket_lbp_mean,bucket_lbp_std,bucket_lbp_median,bucket_percent_dark_pixels,bucket_percent_white_pixels,bucket_percent_red_pixels,bucket_percent_blue_pixels,bucket_percent_outlier_bright_pixels,bucket_percent_outlier_dark_pixels
0,images/100.jpg,success,8.844754,143.157422,127.225247,3.760556,57.882412,42.754618,0.235202,0.304292,...,энтропия_lbp:средняя,среднее_lbp:высокое,разброс_lbp:средний,медиана_lbp:типичная,темные_пиксели:нет,белые_пиксели:единичные,красные_пиксели:много,синие_пиксели:нет,яркие_выбросы:нет,темные_выбросы:нет
1,images/1000.jpg,success,9.441791,130.862138,202.150413,2.038567,23.189567,14.328646,0.229396,0.303959,...,энтропия_lbp:высокая,среднее_lbp:среднее,разброс_lbp:высокий,медиана_lbp:типичная,темные_пиксели:нет,белые_пиксели:нет,красные_пиксели:преобладают,синие_пиксели:нет,яркие_выбросы:много,темные_выбросы:умеренно

## Шаг 2. Бакетирование

### 2.1 Анализ распределений и подбор параметров.

In [8]:
# sys.argv = [
#     "/kaggle/working/img2txt/analysis/distribution_analysis.py"
#     "--csv", FEATURES_CSV
# ]
# analysis()

### 2.2 Бакетирование признаков

In [9]:
df = bucket_features_batch(df)

100%|██████████| 4137/4137 [00:00<00:00, 12792.13it/s]

## Шаг 3. Ранжирование (Выбор топ-10 важных признаков XGBoost)

### 3.1 Обучение модели

#### 3.1.1 XGB

In [10]:
optuna_kwargs = {
    "learning_rate": {"type": "float", "low": 0.003, "high": 0.08, "log": True},
    "n_estimators": {"type": "int", "low": 500, "high": 1600},
    "reg_lambda": {"type": "float", "low": 0.5, "high": 6.0},
    "reg_alpha": {"type": "float", "low": 1e-4, "high": 0.3, "log": True},
    "subsample": {"type": "float", "low": 0.6, "high": 1.0},
    "colsample_bytree": {"type": "float", "low": 0.55, "high": 1.0},
    "min_child_weight": {"type": "int", "low": 1, "high": 8},
    "gamma": {"type": "float", "low": 0.0, "high": 5.0},
    "max_bin": {"type": "categorical", "choices": [128, 256, 512]},
    "max_depth": {"type": "int", "low": 4, "high": 7},
}

result = xgb(
    features_csv=FEATURES_CSV,
    annotations_csv=ANNOTATIONS_CSV,
    feature_set="selected_buckets",
    model_type="xgb",
    n_trials=30,
    checkpoint_path="/kaggle/working/xgb_importance.pkl",
    calibrate_label_bias=True,
    kwargs=optuna_kwargs,
)

======================================================================
  XGBoost importance model
======================================================================

[I 2026-04-22 13:33:01,334] A new study created in memory with name: no-name-04cdde06-4a31-4f49-819d-cc9ef61be7a0
[I 2026-04-22 13:33:10,702] Trial 0 finished with value: 0.6158373015873017 and parameters: {'learning_rate': 0.02081753027680346, 'n_estimators': 913, 'reg_lambda': 2.2516076734650277, 'reg_alpha': 0.00034788364089838824, 'subsample': 0.7511234688764071, 'colsample_bytree': 0.9449196745542713, 'min_child_weight': 5, 'gamma': 0.490883090300579, 'max_bin': 128, 'max_depth': 7}. Best is trial 0 with value: 0.6158373015873017.
[I 2026-04-22 13:33:25,955] Trial 1 finished with value: 0.6158809523809523 and parameters: {'learning_rate': 0.007012023114739468, 'n_estimators': 813, 'reg_lambda': 3.656928588575444, 'reg_alpha': 0.016886952768850588, 'subsample': 0.7756296926165571, 'colsample_bytree': 0.7632434627572626, 'min_child_weight': 7, 'gamma': 3.0830733698150077, 'max_bin': 128, 'max_depth': 7}. Best is trial 1 with value: 0.6158809523809523.
[I 2026-04-22 13:33:38,707] Trial 2 finished with value: 0.6161369047619047 and parameters: {'learning_rate': 0.008213533495207564, 'n_estimators': 663, 'reg_lambda': 4.456447511095016, 'reg_alpha': 0.0029878260043958798, 'subsample': 0.7022254776655218, 'colsample_bytree': 0.7877098952369884, 'min_child_weight': 5, 'gamma': 4.038645450833595, 'max_bin': 128, 'max_depth': 4}. Best is trial 2 with value: 0.6161369047619047.
[I 2026-04-22 13:33:46,208] Trial 3 finished with value: 0.6236825396825396 and parameters: {'learning_rate': 0.04625299618360233, 'n_estimators': 1192, 'reg_lambda': 2.4837704802519336, 'reg_alpha': 0.001089500628020923, 'subsample': 0.7893703928680027, 'colsample_bytree': 0.6329296605608585, 'min_child_weight': 3, 'gamma': 0.2797324368867887, 'max_bin': 512, 'max_depth': 7}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:33:53,668] Trial 4 finished with value: 0.6188313492063492 and parameters: {'learning_rate': 0.02055906491566383, 'n_estimators': 537, 'reg_lambda': 1.370648808851958, 'reg_alpha': 0.006459088426425678, 'subsample': 0.9460807706596819, 'colsample_bytree': 0.8584113142698817, 'min_child_weight': 8, 'gamma': 4.449684211813159, 'max_bin': 128, 'max_depth': 4}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:33:59,173] Trial 5 finished with value: 0.6114742063492065 and parameters: {'learning_rate': 0.0688640312493699, 'n_estimators': 1434, 'reg_lambda': 0.7849866394207496, 'reg_alpha': 0.0001425714270194649, 'subsample': 0.6699324842641013, 'colsample_bytree': 0.7389264037920614, 'min_child_weight': 1, 'gamma': 2.262605844043754, 'max_bin': 128, 'max_depth': 7}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:34:08,053] Trial 6 finished with value: 0.6192460317460318 and parameters: {'learning_rate': 0.01491059696879384, 'n_estimators': 942, 'reg_lambda': 1.0410678077480429, 'reg_alpha': 0.000716010902349896, 'subsample': 0.683672476209388, 'colsample_bytree': 0.9044747401550963, 'min_child_weight': 4, 'gamma': 2.179265595958322, 'max_bin': 256, 'max_depth': 5}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:34:16,111] Trial 7 finished with value: 0.6169960317460318 and parameters: {'learning_rate': 0.030461136680162797, 'n_estimators': 1497, 'reg_lambda': 5.501272567117661, 'reg_alpha': 0.00010449503627285372, 'subsample': 0.8960052863312101, 'colsample_bytree': 0.5625579478458985, 'min_child_weight': 7, 'gamma': 2.84969112707019, 'max_bin': 512, 'max_depth': 5}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:34:23,194] Trial 8 finished with value: 0.6134960317460317 and parameters: {'learning_rate': 0.03906241284310833, 'n_estimators': 1396, 'reg_lambda': 1.173312023612883, 'reg_alpha': 0.05316607314668344, 'subsample': 0.8587669454607156, 'colsample_bytree': 0.8268542582132092, 'min_child_weight': 8, 'gamma': 1.422521375890176, 'max_bin': 256, 'max_depth': 4}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:34:34,162] Trial 9 finished with value: 0.6152142857142857 and parameters: {'learning_rate': 0.009949582426652772, 'n_estimators': 1452, 'reg_lambda': 1.5320561506183883, 'reg_alpha': 0.06949769646542293, 'subsample': 0.8588492099795514, 'colsample_bytree': 0.6061429556031187, 'min_child_weight': 4, 'gamma': 3.1938471935513837, 'max_bin': 128, 'max_depth': 4}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:34:56,156] Trial 10 finished with value: 0.613375 and parameters: {'learning_rate': 0.0030971584742719082, 'n_estimators': 1193, 'reg_lambda': 2.6475484248453998, 'reg_alpha': 0.0014853364330868093, 'subsample': 0.9972646175395298, 'colsample_bytree': 0.6581603665663799, 'min_child_weight': 1, 'gamma': 0.013332389956729696, 'max_bin': 512, 'max_depth': 6}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:35:01,598] Trial 11 finished with value: 0.6114960317460318 and parameters: {'learning_rate': 0.07024885104427091, 'n_estimators': 1160, 'reg_lambda': 2.4688605197707285, 'reg_alpha': 0.0009341431744575685, 'subsample': 0.6617997292075962, 'colsample_bytree': 0.9894430595173225, 'min_child_weight': 3, 'gamma': 1.5507405122927047, 'max_bin': 256, 'max_depth': 6}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:35:13,123] Trial 12 finished with value: 0.6231507936507936 and parameters: {'learning_rate': 0.013592972814095465, 'n_estimators': 1045, 'reg_lambda': 3.5043273797411825, 'reg_alpha': 0.0008284096654623366, 'subsample': 0.7224516096883308, 'colsample_bytree': 0.8917760263229619, 'min_child_weight': 3, 'gamma': 0.9757364992706301, 'max_bin': 512, 'max_depth': 5}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:35:20,542] Trial 13 finished with value: 0.614857142857143 and parameters: {'learning_rate': 0.04096209646147119, 'n_estimators': 1223, 'reg_lambda': 3.6839245834166423, 'reg_alpha': 0.007776894902537825, 'subsample': 0.7980782187769049, 'colsample_bytree': 0.7058405761122063, 'min_child_weight': 2, 'gamma': 0.8164990406986814, 'max_bin': 512, 'max_depth': 6}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:35:32,226] Trial 14 finished with value: 0.6093511904761906 and parameters: {'learning_rate': 0.012822146778814046, 'n_estimators': 1062, 'reg_lambda': 4.415068524417915, 'reg_alpha': 0.0003537831397642696, 'subsample': 0.6103376579231948, 'colsample_bytree': 0.6573125690974578, 'min_child_weight': 3, 'gamma': 1.1052341176944258, 'max_bin': 512, 'max_depth': 5}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:35:53,113] Trial 15 finished with value: 0.6122837301587302 and parameters: {'learning_rate': 0.004721960916423037, 'n_estimators': 1309, 'reg_lambda': 3.2651683660282336, 'reg_alpha': 0.0023560039449906796, 'subsample': 0.7463326768109942, 'colsample_bytree': 0.8750911654898361, 'min_child_weight': 3, 'gamma': 0.15743416923243914, 'max_bin': 512, 'max_depth': 6}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:36:01,520] Trial 16 finished with value: 0.6183214285714287 and parameters: {'learning_rate': 0.02836562185620359, 'n_estimators': 1592, 'reg_lambda': 4.668742214428392, 'reg_alpha': 0.0003520143539103292, 'subsample': 0.8294897550599944, 'colsample_bytree': 0.5542653321652056, 'min_child_weight': 2, 'gamma': 1.7719324710379933, 'max_bin': 512, 'max_depth': 5}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:36:07,961] Trial 17 finished with value: 0.5964007936507937 and parameters: {'learning_rate': 0.05061955774002428, 'n_estimators': 1024, 'reg_lambda': 2.008582958094696, 'reg_alpha': 0.01711684686203458, 'subsample': 0.7243881616174896, 'colsample_bytree': 0.8127181036932722, 'min_child_weight': 6, 'gamma': 0.7199908847167197, 'max_bin': 512, 'max_depth': 7}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:36:17,519] Trial 18 finished with value: 0.6214067460317461 and parameters: {'learning_rate': 0.02231421797109907, 'n_estimators': 847, 'reg_lambda': 3.055133637746789, 'reg_alpha': 0.2907006537496564, 'subsample': 0.609056129622831, 'colsample_bytree': 0.6887276702073909, 'min_child_weight': 2, 'gamma': 1.1152092477483118, 'max_bin': 512, 'max_depth': 6}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:36:29,889] Trial 19 finished with value: 0.6233789682539683 and parameters: {'learning_rate': 0.011458751517663407, 'n_estimators': 1059, 'reg_lambda': 3.8634840463586455, 'reg_alpha': 0.0007451373788823012, 'subsample': 0.8046254275830119, 'colsample_bytree': 0.942929191967382, 'min_child_weight': 4, 'gamma': 0.29849835241123557, 'max_bin': 512, 'max_depth': 5}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:36:48,964] Trial 20 finished with value: 0.6142142857142856 and parameters: {'learning_rate': 0.005473724516645305, 'n_estimators': 1312, 'reg_lambda': 5.970729702933049, 'reg_alpha': 0.004098571833749637, 'subsample': 0.9050964177230487, 'colsample_bytree': 0.9725773843729606, 'min_child_weight': 4, 'gamma': 0.4001993758209439, 'max_bin': 512, 'max_depth': 7}. Best is trial 3 with value: 0.6236825396825396.
[I 2026-04-22 13:37:00,234] Trial 21 finished with value: 0.6299900793650794 and parameters: {'learning_rate': 0.012003521459161039, 'n_estimators': 1068, 'reg_lambda': 3.838581905814251, 'reg_alpha': 0.0007207860441757997, 'subsample': 0.7955384667275734, 'colsample_bytree': 0.9221258222564838, 'min_child_weight': 3, 'gamma': 0.006110552386934809, 'max_bin': 512, 'max_depth': 5}. Best is trial 21 with value: 0.6299900793650794.
[I 2026-04-22 13:37:12,662] Trial 22 finished with value: 0.6166448412698413 and parameters: {'learning_rate': 0.010576407850935969, 'n_estimators': 1117, 'reg_lambda': 4.093227150460116, 'reg_alpha': 0.0016210264610947893, 'subsample': 0.8096759670246771, 'colsample_bytree': 0.9404230699610143, 'min_child_weight': 5, 'gamma': 0.11998836172698635, 'max_bin': 512, 'max_depth': 5}. Best is trial 21 with value: 0.6299900793650794.
[I 2026-04-22 13:37:23,341] Trial 23 finished with value: 0.620765873015873 and parameters: {'learning_rate': 0.016193464090716064, 'n_estimators': 1270, 'reg_lambda': 3.013879548951839, 'reg_alpha': 0.00023712547073850162, 'subsample': 0.7795524265687254, 'colsample_bytree': 0.9259905138237305, 'min_child_weight': 4, 'gamma': 0.5834751744917758, 'max_bin': 512, 'max_depth': 5}. Best is trial 21 with value: 0.6299900793650794.
[I 2026-04-22 13:37:41,343] Trial 24 finished with value: 0.6195198412698413 and parameters: {'learning_rate': 0.0062680028860552335, 'n_estimators': 773, 'reg_lambda': 5.115492794619335, 'reg_alpha': 0.0008716698688678642, 'subsample': 0.8381434308352734, 'colsample_bytree': 0.8252765894827654, 'min_child_weight': 2, 'gamma': 0.004174104657801974, 'max_bin': 512, 'max_depth': 6}. Best is trial 21 with value: 0.6299900793650794.
[I 2026-04-22 13:37:54,369] Trial 25 finished with value: 0.620811507936508 and parameters: {'learning_rate': 0.009282083301991026, 'n_estimators': 964, 'reg_lambda': 3.9619328531745936, 'reg_alpha': 0.0005188760479842097, 'subsample': 0.7752822444473215, 'colsample_bytree': 0.996061704646968, 'min_child_weight': 3, 'gamma': 1.8710593297651013, 'max_bin': 256, 'max_depth': 5}. Best is trial 21 with value: 0.6299900793650794.
[I 2026-04-22 13:38:03,626] Trial 26 finished with value: 0.6209285714285714 and parameters: {'learning_rate': 0.017719959593556215, 'n_estimators': 1114, 'reg_lambda': 1.8724281613484357, 'reg_alpha': 0.001515604231900964, 'subsample': 0.8787140710950524, 'colsample_bytree': 0.847753815681816, 'min_child_weight': 6, 'gamma': 1.2893160111359756, 'max_bin': 512, 'max_depth': 4}. Best is trial 21 with value: 0.6299900793650794.
[I 2026-04-22 13:38:27,562] Trial 27 finished with value: 0.613373015873016 and parameters: {'learning_rate': 0.0038595624378996796, 'n_estimators': 993, 'reg_lambda': 2.834702013663404, 'reg_alpha': 0.00018562902991764142, 'subsample': 0.8214879926981508, 'colsample_bytree': 0.6269569003552222, 'min_child_weight': 4, 'gamma': 0.39954124946957376, 'max_bin': 512, 'max_depth': 6}. Best is trial 21 with value: 0.6299900793650794.
[I 2026-04-22 13:38:35,320] Trial 28 finished with value: 0.6145376984126985 and parameters: {'learning_rate': 0.0276915837030767, 'n_estimators': 744, 'reg_lambda': 4.830342763175451, 'reg_alpha': 0.0022572405320399227, 'subsample': 0.9327271114040793, 'colsample_bytree': 0.9539294683383043, 'min_child_weight': 2, 'gamma': 0.7882077966533692, 'max_bin': 512, 'max_depth': 5}. Best is trial 21 with value: 0.6299900793650794.
[I 2026-04-22 13:38:45,735] Trial 29 finished with value: 0.621045634920635 and parameters: {'learning_rate': 0.010716978641969006, 'n_estimators': 889, 'reg_lambda': 2.2695372988336784, 'reg_alpha': 0.0004762612752868677, 'subsample': 0.7582711032867845, 'colsample_bytree': 0.9192164712805425, 'min_child_weight': 5, 'gamma': 3.888605453111039, 'max_bin': 256, 'max_depth': 7}. Best is trial 21 with value: 0.6299900793650794.

======================================================================
  BEST PARAMS
======================================================================
{'learning_rate': 0.012003521459161039, 'n_estimators': 1068, 'reg_lambda': 3.838581905814251, 'reg_alpha': 0.0007207860441757997, 'subsample': 0.7955384667275734, 'colsample_bytree': 0.9221258222564838, 'min_child_weight': 3, 'gamma': 0.006110552386934809, 'max_bin': 512, 'max_depth': 5}
Best score: 0.6300
Final score: 0.6300
Calibration: alpha=0.325, score 0.6300 -> 0.6355, precision 0.5910 -> 0.5960, recall 0.6690 -> 0.6750
Targeted calibration labels: palette, borders, delta_V_top_bottom, delta_V_left_right, delta_V_center_periphery, structure_order, delta_H_center_periphery, elongation

Most under-selected labels after calibration:
  palette: true=0.027, selected=0.000, delta=-0.027, recall@10=0.000
  delta_V_top_bottom: true=0.032, selected=0.007, delta=-0.025, recall@10=0.143
  delta_H_center_periphery: true=0.033, selected=0.012, delta=-0.021, recall@10=0.207
  delta_V_left_right: true=0.016, selected=0.000, delta=-0.016, recall@10=0.000
  perimeter: true=0.050, selected=0.035, delta=-0.015, recall@10=0.477
  delta_V_center_periphery: true=0.020, selected=0.006, delta=-0.014, recall@10=0.167
  borders: true=0.031, selected=0.018, delta=-0.013, recall@10=0.296
  structure_order: true=0.017, selected=0.005, delta=-0.012, recall@10=0.200

Most over-selected labels after calibration:
  asymmetry: true=0.072, selected=0.100, delta=0.028, precision=0.630
  delta_V_inner_rim: true=0.069, selected=0.095, delta=0.026, precision=0.632
  color_homogeneity: true=0.077, selected=0.100, delta=0.023, precision=0.680
  dominant_hue: true=0.055, selected=0.077, delta=0.022, precision=0.545
  delta_S_left_right: true=0.047, selected=0.065, delta=0.018, precision=0.415
  contrast: true=0.056, selected=0.073, delta=0.017, precision=0.493
  std_H_lesion: true=0.030, selected=0.039, delta=0.009, precision=0.359
  eccentricity: true=0.036, selected=0.044, delta=0.008, precision=0.386
Checkpoint saved to: /kaggle/working/xgb_importance.pkl

In [11]:
result = xgb(
    features_csv=FEATURES_CSV,
    annotations_csv=ANNOTATIONS_CSV,
    feature_set="numeric_only",
    model_type="xgb",
    n_trials=30,
    checkpoint_path="/kaggle/working/xgb_numeric.pkl",
    calibrate_label_bias=True,
    kwargs=optuna_kwargs,
)

======================================================================
  XGBoost importance model
======================================================================

[I 2026-04-22 13:38:59,251] A new study created in memory with name: no-name-af313757-6007-4a5b-b5ae-c84516a0ed82
[I 2026-04-22 13:39:05,134] Trial 0 finished with value: 0.6223035714285714 and parameters: {'learning_rate': 0.007864755004903332, 'n_estimators': 1238, 'reg_lambda': 2.159451704666281, 'reg_alpha': 0.0030667667256469924, 'subsample': 0.9242795359568242, 'colsample_bytree': 0.9904013490787407, 'min_child_weight': 6, 'gamma': 4.276337474424644, 'max_bin': 512, 'max_depth': 7}. Best is trial 0 with value: 0.6223035714285714.
[I 2026-04-22 13:39:09,744] Trial 1 finished with value: 0.6229007936507938 and parameters: {'learning_rate': 0.033192148861190686, 'n_estimators': 508, 'reg_lambda': 4.738257648318553, 'reg_alpha': 0.23403549433039092, 'subsample': 0.6445415985580548, 'colsample_bytree': 0.7852969255905533, 'min_child_weight': 5, 'gamma': 0.4002029558476955, 'max_bin': 512, 'max_depth': 6}. Best is trial 1 with value: 0.6229007936507938.
[I 2026-04-22 13:39:14,943] Trial 2 finished with value: 0.6137182539682541 and parameters: {'learning_rate': 0.009527955340142925, 'n_estimators': 1285, 'reg_lambda': 2.6869300140005654, 'reg_alpha': 0.008057251141633892, 'subsample': 0.6010977930000633, 'colsample_bytree': 0.7151052238165173, 'min_child_weight': 3, 'gamma': 0.7445876963112863, 'max_bin': 128, 'max_depth': 4}. Best is trial 1 with value: 0.6229007936507938.
[I 2026-04-22 13:39:17,985] Trial 3 finished with value: 0.6158293650793651 and parameters: {'learning_rate': 0.04190384075894364, 'n_estimators': 1091, 'reg_lambda': 5.394039872595478, 'reg_alpha': 0.0016201697786402166, 'subsample': 0.8204076457742238, 'colsample_bytree': 0.7105503212432209, 'min_child_weight': 6, 'gamma': 4.224321140184589, 'max_bin': 128, 'max_depth': 7}. Best is trial 1 with value: 0.6229007936507938.
[I 2026-04-22 13:39:21,693] Trial 4 finished with value: 0.6091230158730159 and parameters: {'learning_rate': 0.04226890272919238, 'n_estimators': 1044, 'reg_lambda': 2.350458509220312, 'reg_alpha': 0.001345472140003974, 'subsample': 0.6503084373192192, 'colsample_bytree': 0.7954257550580519, 'min_child_weight': 3, 'gamma': 1.1965278421201797, 'max_bin': 256, 'max_depth': 7}. Best is trial 1 with value: 0.6229007936507938.
[I 2026-04-22 13:39:24,649] Trial 5 finished with value: 0.6203630952380953 and parameters: {'learning_rate': 0.057962498305426866, 'n_estimators': 734, 'reg_lambda': 4.70678474894747, 'reg_alpha': 0.0012558134835780235, 'subsample': 0.6923917415863708, 'colsample_bytree': 0.6056958348281308, 'min_child_weight': 5, 'gamma': 1.478582241601596, 'max_bin': 256, 'max_depth': 4}. Best is trial 1 with value: 0.6229007936507938.
[I 2026-04-22 13:39:27,649] Trial 6 finished with value: 0.6068313492063492 and parameters: {'learning_rate': 0.03257660688311731, 'n_estimators': 1221, 'reg_lambda': 4.356214177566694, 'reg_alpha': 0.0027398626404982478, 'subsample': 0.9974888730210503, 'colsample_bytree': 0.9881148283068255, 'min_child_weight': 5, 'gamma': 3.5255984855435467, 'max_bin': 512, 'max_depth': 5}. Best is trial 1 with value: 0.6229007936507938.
[I 2026-04-22 13:39:35,353] Trial 7 finished with value: 0.6208511904761905 and parameters: {'learning_rate': 0.007273210903006745, 'n_estimators': 1193, 'reg_lambda': 2.7551823346728503, 'reg_alpha': 0.019214706001619588, 'subsample': 0.6321609157564404, 'colsample_bytree': 0.6960149696698359, 'min_child_weight': 1, 'gamma': 1.067092082726523, 'max_bin': 256, 'max_depth': 6}. Best is trial 1 with value: 0.6229007936507938.
[I 2026-04-22 13:39:44,415] Trial 8 finished with value: 0.6131289682539682 and parameters: {'learning_rate': 0.00438888958579979, 'n_estimators': 642, 'reg_lambda': 1.419931778597174, 'reg_alpha': 0.0018559165745957625, 'subsample': 0.6649268790245079, 'colsample_bytree': 0.7066900246512846, 'min_child_weight': 1, 'gamma': 3.5872332910021236, 'max_bin': 512, 'max_depth': 6}. Best is trial 1 with value: 0.6229007936507938.
[I 2026-04-22 13:39:47,176] Trial 9 finished with value: 0.6083968253968254 and parameters: {'learning_rate': 0.05079179085058996, 'n_estimators': 1146, 'reg_lambda': 1.3639942296008503, 'reg_alpha': 0.16401408290156022, 'subsample': 0.8928629372984448, 'colsample_bytree': 0.9109015970673098, 'min_child_weight': 1, 'gamma': 3.579315336716279, 'max_bin': 512, 'max_depth': 6}. Best is trial 1 with value: 0.6229007936507938.
[I 2026-04-22 13:39:51,667] Trial 10 finished with value: 0.6232063492063492 and parameters: {'learning_rate': 0.021882061942797522, 'n_estimators': 1588, 'reg_lambda': 3.9607740849359288, 'reg_alpha': 0.00015129884156445234, 'subsample': 0.7641420783104096, 'colsample_bytree': 0.8255125465562119, 'min_child_weight': 8, 'gamma': 0.05168003479984323, 'max_bin': 512, 'max_depth': 5}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:39:56,181] Trial 11 finished with value: 0.6178928571428572 and parameters: {'learning_rate': 0.022070777515069348, 'n_estimators': 1589, 'reg_lambda': 3.9278626599781803, 'reg_alpha': 0.00011605277832803896, 'subsample': 0.7464757708795269, 'colsample_bytree': 0.8382008069943275, 'min_child_weight': 8, 'gamma': 0.06396830375542528, 'max_bin': 512, 'max_depth': 5}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:40:00,890] Trial 12 finished with value: 0.6156428571428572 and parameters: {'learning_rate': 0.01795215221295272, 'n_estimators': 501, 'reg_lambda': 5.969903940464786, 'reg_alpha': 0.2713641007948529, 'subsample': 0.7542895165582812, 'colsample_bytree': 0.8477162752738643, 'min_child_weight': 8, 'gamma': 2.254059498851096, 'max_bin': 512, 'max_depth': 5}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:40:05,473] Trial 13 finished with value: 0.6223432539682541 and parameters: {'learning_rate': 0.025001888783365563, 'n_estimators': 1586, 'reg_lambda': 3.488706218945001, 'reg_alpha': 0.00015476615169337013, 'subsample': 0.8333568406493584, 'colsample_bytree': 0.8884467551450945, 'min_child_weight': 7, 'gamma': 0.05348564852788234, 'max_bin': 512, 'max_depth': 5}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:40:12,171] Trial 14 finished with value: 0.6156646825396825 and parameters: {'learning_rate': 0.012628138642463682, 'n_estimators': 968, 'reg_lambda': 4.9360151279335565, 'reg_alpha': 0.02995570298218646, 'subsample': 0.7364929673015141, 'colsample_bytree': 0.7767157192261769, 'min_child_weight': 3, 'gamma': 2.2140625217318988, 'max_bin': 512, 'max_depth': 6}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:40:14,885] Trial 15 finished with value: 0.6154543650793651 and parameters: {'learning_rate': 0.0769998686168298, 'n_estimators': 1391, 'reg_lambda': 3.915146241192222, 'reg_alpha': 0.06946003389178275, 'subsample': 0.7862912223568655, 'colsample_bytree': 0.5586502426927744, 'min_child_weight': 7, 'gamma': 0.5381860631583423, 'max_bin': 128, 'max_depth': 4}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:40:20,461] Trial 16 finished with value: 0.6187956349206349 and parameters: {'learning_rate': 0.014597811555116684, 'n_estimators': 869, 'reg_lambda': 5.361587387248024, 'reg_alpha': 0.00030383792822531426, 'subsample': 0.6948736577537372, 'colsample_bytree': 0.8983006020021826, 'min_child_weight': 4, 'gamma': 1.7990728162623215, 'max_bin': 512, 'max_depth': 5}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:40:24,880] Trial 17 finished with value: 0.6196369047619048 and parameters: {'learning_rate': 0.026303037798170913, 'n_estimators': 1436, 'reg_lambda': 3.4963435527415236, 'reg_alpha': 0.00043250330616862175, 'subsample': 0.8612074980195438, 'colsample_bytree': 0.8135494262876816, 'min_child_weight': 7, 'gamma': 0.5603680444314337, 'max_bin': 512, 'max_depth': 6}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:40:33,446] Trial 18 finished with value: 0.6098234126984128 and parameters: {'learning_rate': 0.004258141242270559, 'n_estimators': 844, 'reg_lambda': 4.223127456368065, 'reg_alpha': 0.009141503743805788, 'subsample': 0.6998427884220735, 'colsample_bytree': 0.6539063473466595, 'min_child_weight': 4, 'gamma': 2.842627435089002, 'max_bin': 256, 'max_depth': 5}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:40:36,443] Trial 19 finished with value: 0.622204365079365 and parameters: {'learning_rate': 0.033663986704106745, 'n_estimators': 501, 'reg_lambda': 0.8153622843549098, 'reg_alpha': 0.07326267910920312, 'subsample': 0.7694753316615679, 'colsample_bytree': 0.7528600318572897, 'min_child_weight': 6, 'gamma': 4.857097951596391, 'max_bin': 128, 'max_depth': 6}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:40:43,030] Trial 20 finished with value: 0.6116587301587302 and parameters: {'learning_rate': 0.018152120618989402, 'n_estimators': 673, 'reg_lambda': 5.8263748812850125, 'reg_alpha': 0.0005298345349662724, 'subsample': 0.6168090244742879, 'colsample_bytree': 0.9498509050142846, 'min_child_weight': 2, 'gamma': 0.0206695514340276, 'max_bin': 512, 'max_depth': 7}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:40:47,565] Trial 21 finished with value: 0.6179345238095239 and parameters: {'learning_rate': 0.026238606490239375, 'n_estimators': 1576, 'reg_lambda': 3.3918411688198, 'reg_alpha': 0.0001096256337571302, 'subsample': 0.8408650044351321, 'colsample_bytree': 0.8837172577737415, 'min_child_weight': 7, 'gamma': 0.30071795840821236, 'max_bin': 512, 'max_depth': 5}. Best is trial 10 with value: 0.6232063492063492.
[I 2026-04-22 13:40:51,945] Trial 22 finished with value: 0.6245535714285715 and parameters: {'learning_rate': 0.02344904562091069, 'n_estimators': 1482, 'reg_lambda': 3.0891680259237186, 'reg_alpha': 0.00020692195160681276, 'subsample': 0.8083782144522911, 'colsample_bytree': 0.8653303821810976, 'min_child_weight': 8, 'gamma': 0.9137946563751154, 'max_bin': 512, 'max_depth': 5}. Best is trial 22 with value: 0.6245535714285715.
[I 2026-04-22 13:40:57,475] Trial 23 finished with value: 0.6160674603174603 and parameters: {'learning_rate': 0.010941211717829207, 'n_estimators': 1413, 'reg_lambda': 2.9457452940120734, 'reg_alpha': 0.0002455692546859738, 'subsample': 0.7985210487709615, 'colsample_bytree': 0.8488080813170098, 'min_child_weight': 8, 'gamma': 0.9359943620172649, 'max_bin': 512, 'max_depth': 4}. Best is trial 22 with value: 0.6245535714285715.
[I 2026-04-22 13:41:02,291] Trial 24 finished with value: 0.619609126984127 and parameters: {'learning_rate': 0.020460628769326448, 'n_estimators': 1453, 'reg_lambda': 4.827031451869204, 'reg_alpha': 0.0006531074612465084, 'subsample': 0.7201946633222518, 'colsample_bytree': 0.757159467409979, 'min_child_weight': 8, 'gamma': 1.5468031652323098, 'max_bin': 512, 'max_depth': 5}. Best is trial 22 with value: 0.6245535714285715.
[I 2026-04-22 13:41:06,661] Trial 25 finished with value: 0.6175257936507936 and parameters: {'learning_rate': 0.035245995447628, 'n_estimators': 1349, 'reg_lambda': 4.010613897298461, 'reg_alpha': 0.00022198266041482723, 'subsample': 0.9229964238878574, 'colsample_bytree': 0.8222381076199016, 'min_child_weight': 6, 'gamma': 0.6912047126786156, 'max_bin': 512, 'max_depth': 6}. Best is trial 22 with value: 0.6245535714285715.
[I 2026-04-22 13:41:11,977] Trial 26 finished with value: 0.616470238095238 and parameters: {'learning_rate': 0.014578675423026623, 'n_estimators': 1497, 'reg_lambda': 4.516723783745554, 'reg_alpha': 0.0007091013410251106, 'subsample': 0.8625394022576772, 'colsample_bytree': 0.9315694415979053, 'min_child_weight': 5, 'gamma': 1.1892988829564441, 'max_bin': 512, 'max_depth': 5}. Best is trial 22 with value: 0.6245535714285715.
[I 2026-04-22 13:41:26,108] Trial 27 finished with value: 0.611734126984127 and parameters: {'learning_rate': 0.003090752130334755, 'n_estimators': 1514, 'reg_lambda': 5.192620084622163, 'reg_alpha': 0.020401859694794664, 'subsample': 0.6675881973324893, 'colsample_bytree': 0.8688557093507991, 'min_child_weight': 7, 'gamma': 0.34808982462101645, 'max_bin': 512, 'max_depth': 4}. Best is trial 22 with value: 0.6245535714285715.
[I 2026-04-22 13:41:29,079] Trial 28 finished with value: 0.6145099206349207 and parameters: {'learning_rate': 0.060096612770890026, 'n_estimators': 917, 'reg_lambda': 3.0594157705923193, 'reg_alpha': 0.060726408587661616, 'subsample': 0.7804306067071632, 'colsample_bytree': 0.7998186581655065, 'min_child_weight': 8, 'gamma': 1.9001787107591066, 'max_bin': 128, 'max_depth': 6}. Best is trial 22 with value: 0.6245535714285715.
[I 2026-04-22 13:41:35,656] Trial 29 finished with value: 0.6216369047619048 and parameters: {'learning_rate': 0.007185029559863639, 'n_estimators': 1328, 'reg_lambda': 1.8092585596160653, 'reg_alpha': 0.0035589435907230843, 'subsample': 0.979996840724762, 'colsample_bytree': 0.7555281805045676, 'min_child_weight': 6, 'gamma': 2.8262381346252115, 'max_bin': 256, 'max_depth': 7}. Best is trial 22 with value: 0.6245535714285715.

======================================================================
  BEST PARAMS
======================================================================
{'learning_rate': 0.02344904562091069, 'n_estimators': 1482, 'reg_lambda': 3.0891680259237186, 'reg_alpha': 0.00020692195160681276, 'subsample': 0.8083782144522911, 'colsample_bytree': 0.8653303821810976, 'min_child_weight': 8, 'gamma': 0.9137946563751154, 'max_bin': 512, 'max_depth': 5}
Best score: 0.6246
Final score: 0.6246
Calibration: alpha=0.275, score 0.6246 -> 0.6325, precision 0.5860 -> 0.5930, recall 0.6631 -> 0.6720
Targeted calibration labels: palette, borders, delta_V_top_bottom, delta_V_left_right, delta_V_center_periphery, structure_order, delta_H_center_periphery, elongation

Most under-selected labels after calibration:
  delta_V_top_bottom: true=0.032, selected=0.004, delta=-0.028, recall@10=0.036
  palette: true=0.027, selected=0.000, delta=-0.027, recall@10=0.000
  borders: true=0.031, selected=0.008, delta=-0.023, recall@10=0.148
  perimeter: true=0.050, selected=0.033, delta=-0.017, recall@10=0.477
  delta_V_left_right: true=0.016, selected=0.002, delta=-0.014, recall@10=0.071
  delta_V_center_periphery: true=0.020, selected=0.010, delta=-0.010, recall@10=0.278
  fractal_dimension: true=0.043, selected=0.035, delta=-0.008, recall@10=0.500
  structure_order: true=0.017, selected=0.009, delta=-0.008, recall@10=0.267

Most over-selected labels after calibration:
  asymmetry: true=0.072, selected=0.100, delta=0.028, precision=0.630
  delta_V_inner_rim: true=0.069, selected=0.093, delta=0.024, precision=0.613
  color_homogeneity: true=0.077, selected=0.100, delta=0.023, precision=0.680
  dominant_hue: true=0.055, selected=0.072, delta=0.017, precision=0.542
  contrast: true=0.056, selected=0.071, delta=0.015, precision=0.521
  delta_S_left_right: true=0.047, selected=0.061, delta=0.014, precision=0.443
  std_H_lesion: true=0.030, selected=0.043, delta=0.013, precision=0.302
  delta_S_center_periphery: true=0.035, selected=0.042, delta=0.007, precision=0.286
Checkpoint saved to: /kaggle/working/xgb_numeric.pkl

In [12]:
result = xgb(
    features_csv=FEATURES_CSV,
    annotations_csv=ANNOTATIONS_CSV,
    feature_set="all_buckets",
    model_type="xgb",
    n_trials=30,
    checkpoint_path="/kaggle/working/xgb_buckets.pkl",
    calibrate_label_bias=True,
    kwargs=optuna_kwargs,
)

======================================================================
  XGBoost importance model
======================================================================

[I 2026-04-22 13:41:42,005] A new study created in memory with name: no-name-af608e95-36e8-44fe-a212-ef259a08638e
[I 2026-04-22 13:41:58,372] Trial 0 finished with value: 0.6133035714285715 and parameters: {'learning_rate': 0.018785147532894772, 'n_estimators': 1272, 'reg_lambda': 3.994685707423318, 'reg_alpha': 0.08993178131678815, 'subsample': 0.6836804546190207, 'colsample_bytree': 0.7724064194604439, 'min_child_weight': 2, 'gamma': 4.6745706729919725, 'max_bin': 512, 'max_depth': 6}. Best is trial 0 with value: 0.6133035714285715.
[I 2026-04-22 13:42:14,732] Trial 1 finished with value: 0.6178035714285715 and parameters: {'learning_rate': 0.019292869832649807, 'n_estimators': 1141, 'reg_lambda': 2.8434381986942583, 'reg_alpha': 0.0002485249827307118, 'subsample': 0.6487960192946581, 'colsample_bytree': 0.6256453988504938, 'min_child_weight': 2, 'gamma': 2.4630849922184774, 'max_bin': 512, 'max_depth': 7}. Best is trial 1 with value: 0.6178035714285715.
[I 2026-04-22 13:42:48,419] Trial 2 finished with value: 0.6172896825396825 and parameters: {'learning_rate': 0.0034199721453670165, 'n_estimators': 532, 'reg_lambda': 1.2071815636064693, 'reg_alpha': 0.023842887626001664, 'subsample': 0.9660388557253781, 'colsample_bytree': 0.909700171394195, 'min_child_weight': 7, 'gamma': 2.9718152487929506, 'max_bin': 128, 'max_depth': 5}. Best is trial 1 with value: 0.6178035714285715.
[I 2026-04-22 13:42:56,844] Trial 3 finished with value: 0.6131150793650795 and parameters: {'learning_rate': 0.06648631000099327, 'n_estimators': 1373, 'reg_lambda': 1.7087563514930304, 'reg_alpha': 0.00033950392836802114, 'subsample': 0.827201987746388, 'colsample_bytree': 0.6529929651713984, 'min_child_weight': 8, 'gamma': 4.421107461174021, 'max_bin': 128, 'max_depth': 4}. Best is trial 1 with value: 0.6178035714285715.
[I 2026-04-22 13:43:12,541] Trial 4 finished with value: 0.6104781746031747 and parameters: {'learning_rate': 0.015221191999551357, 'n_estimators': 715, 'reg_lambda': 4.374123459059074, 'reg_alpha': 0.11057783504442215, 'subsample': 0.9084470678267985, 'colsample_bytree': 0.8428155238829783, 'min_child_weight': 3, 'gamma': 2.0542883102829954, 'max_bin': 128, 'max_depth': 4}. Best is trial 1 with value: 0.6178035714285715.
[I 2026-04-22 13:43:28,389] Trial 5 finished with value: 0.612906746031746 and parameters: {'learning_rate': 0.020153496414010107, 'n_estimators': 972, 'reg_lambda': 4.449195354005207, 'reg_alpha': 0.021683868390096527, 'subsample': 0.9306136420776437, 'colsample_bytree': 0.9741633300585797, 'min_child_weight': 4, 'gamma': 0.5344695223161228, 'max_bin': 512, 'max_depth': 4}. Best is trial 1 with value: 0.6178035714285715.
[I 2026-04-22 13:43:45,589] Trial 6 finished with value: 0.6159761904761905 and parameters: {'learning_rate': 0.012651408226959352, 'n_estimators': 839, 'reg_lambda': 5.650025386115663, 'reg_alpha': 0.00246977171975613, 'subsample': 0.6521099721831306, 'colsample_bytree': 0.6122822824672434, 'min_child_weight': 2, 'gamma': 1.6455062124357545, 'max_bin': 128, 'max_depth': 4}. Best is trial 1 with value: 0.6178035714285715.
[I 2026-04-22 13:43:53,859] Trial 7 finished with value: 0.6128531746031747 and parameters: {'learning_rate': 0.058356751925531365, 'n_estimators': 1286, 'reg_lambda': 3.914824887777067, 'reg_alpha': 0.02553183016708439, 'subsample': 0.8826278004577339, 'colsample_bytree': 0.9407262538203105, 'min_child_weight': 4, 'gamma': 3.044100802618139, 'max_bin': 256, 'max_depth': 5}. Best is trial 1 with value: 0.6178035714285715.
[I 2026-04-22 13:44:06,989] Trial 8 finished with value: 0.6158869047619048 and parameters: {'learning_rate': 0.02625142707716719, 'n_estimators': 1217, 'reg_lambda': 3.998144795012636, 'reg_alpha': 0.025908097126348617, 'subsample': 0.9259325495388934, 'colsample_bytree': 0.6680195622417963, 'min_child_weight': 8, 'gamma': 2.2910490312174643, 'max_bin': 512, 'max_depth': 7}. Best is trial 1 with value: 0.6178035714285715.
[I 2026-04-22 13:44:22,857] Trial 9 finished with value: 0.6159920634920635 and parameters: {'learning_rate': 0.011325852223429531, 'n_estimators': 868, 'reg_lambda': 3.8397447782597305, 'reg_alpha': 0.027321574053319572, 'subsample': 0.6901609478208045, 'colsample_bytree': 0.798015064977826, 'min_child_weight': 6, 'gamma': 4.847933961326383, 'max_bin': 512, 'max_depth': 7}. Best is trial 1 with value: 0.6178035714285715.
[I 2026-04-22 13:44:48,981] Trial 10 finished with value: 0.6200595238095239 and parameters: {'learning_rate': 0.005576449959127959, 'n_estimators': 1547, 'reg_lambda': 2.341549346972644, 'reg_alpha': 0.00010822322718809773, 'subsample': 0.6021463783343237, 'colsample_bytree': 0.5707968667209566, 'min_child_weight': 1, 'gamma': 0.01989482117945718, 'max_bin': 256, 'max_depth': 6}. Best is trial 10 with value: 0.6200595238095239.
[I 2026-04-22 13:45:17,903] Trial 11 finished with value: 0.6189126984126985 and parameters: {'learning_rate': 0.004904521477633033, 'n_estimators': 1576, 'reg_lambda': 2.363350698873095, 'reg_alpha': 0.00010781044844216132, 'subsample': 0.6111368480912193, 'colsample_bytree': 0.5673654953550169, 'min_child_weight': 1, 'gamma': 0.007529541795671699, 'max_bin': 256, 'max_depth': 6}. Best is trial 10 with value: 0.6200595238095239.
[I 2026-04-22 13:45:52,268] Trial 12 finished with value: 0.6197539682539682 and parameters: {'learning_rate': 0.00431487775939964, 'n_estimators': 1592, 'reg_lambda': 2.4301338551151397, 'reg_alpha': 0.00011791404932257426, 'subsample': 0.6109539333233447, 'colsample_bytree': 0.5568534258445891, 'min_child_weight': 1, 'gamma': 0.09046174369673166, 'max_bin': 256, 'max_depth': 6}. Best is trial 10 with value: 0.6200595238095239.
[I 2026-04-22 13:46:14,754] Trial 13 finished with value: 0.620954365079365 and parameters: {'learning_rate': 0.006569433950072228, 'n_estimators': 1589, 'reg_lambda': 0.6153365924757086, 'reg_alpha': 0.0012185382563885906, 'subsample': 0.748720724038493, 'colsample_bytree': 0.5544042621620864, 'min_child_weight': 1, 'gamma': 0.9447358294537287, 'max_bin': 256, 'max_depth': 6}. Best is trial 13 with value: 0.620954365079365.
[I 2026-04-22 13:46:38,786] Trial 14 finished with value: 0.6112837301587302 and parameters: {'learning_rate': 0.007012503227038231, 'n_estimators': 1498, 'reg_lambda': 0.9449421656027376, 'reg_alpha': 0.0016415981587033833, 'subsample': 0.7511757474640854, 'colsample_bytree': 0.7174999473652229, 'min_child_weight': 5, 'gamma': 1.22039401587788, 'max_bin': 256, 'max_depth': 6}. Best is trial 13 with value: 0.620954365079365.
[I 2026-04-22 13:47:00,196] Trial 15 finished with value: 0.6234464285714285 and parameters: {'learning_rate': 0.00785476262585168, 'n_estimators': 1421, 'reg_lambda': 0.5635032113291433, 'reg_alpha': 0.0006605562820798512, 'subsample': 0.7685059897659534, 'colsample_bytree': 0.7102955458155076, 'min_child_weight': 1, 'gamma': 0.8846571613979171, 'max_bin': 256, 'max_depth': 5}. Best is trial 15 with value: 0.6234464285714285.
[I 2026-04-22 13:47:20,999] Trial 16 finished with value: 0.6140099206349207 and parameters: {'learning_rate': 0.008335355828207734, 'n_estimators': 1404, 'reg_lambda': 0.557568054538673, 'reg_alpha': 0.0009427076622739633, 'subsample': 0.7710017172147686, 'colsample_bytree': 0.7216856947900829, 'min_child_weight': 3, 'gamma': 1.0407858559001553, 'max_bin': 256, 'max_depth': 5}. Best is trial 15 with value: 0.6234464285714285.
[I 2026-04-22 13:47:41,704] Trial 17 finished with value: 0.6147202380952381 and parameters: {'learning_rate': 0.008611541883957748, 'n_estimators': 1453, 'reg_lambda': 1.5262795697292302, 'reg_alpha': 0.00627232152044502, 'subsample': 0.8290167651822268, 'colsample_bytree': 0.7079839517866736, 'min_child_weight': 3, 'gamma': 0.8341200997711853, 'max_bin': 256, 'max_depth': 5}. Best is trial 15 with value: 0.6234464285714285.
[I 2026-04-22 13:48:21,943] Trial 18 finished with value: 0.6232936507936508 and parameters: {'learning_rate': 0.0030605696172932525, 'n_estimators': 1073, 'reg_lambda': 0.5680302045322956, 'reg_alpha': 0.0005765851824592687, 'subsample': 0.7388901804961611, 'colsample_bytree': 0.8602211429007091, 'min_child_weight': 5, 'gamma': 1.734668391059774, 'max_bin': 256, 'max_depth': 5}. Best is trial 15 with value: 0.6234464285714285.
[I 2026-04-22 13:48:32,833] Trial 19 finished with value: 0.6117757936507937 and parameters: {'learning_rate': 0.034740599361978826, 'n_estimators': 1075, 'reg_lambda': 1.80304688623662, 'reg_alpha': 0.00050904909528719, 'subsample': 0.80256369510333, 'colsample_bytree': 0.8699154425374772, 'min_child_weight': 6, 'gamma': 3.943141569047288, 'max_bin': 256, 'max_depth': 5}. Best is trial 15 with value: 0.6234464285714285.
[I 2026-04-22 13:49:16,661] Trial 20 finished with value: 0.6098234126984128 and parameters: {'learning_rate': 0.0030230629840069523, 'n_estimators': 988, 'reg_lambda': 5.308147872146013, 'reg_alpha': 0.003299870162566583, 'subsample': 0.710463720909136, 'colsample_bytree': 0.8023919236471438, 'min_child_weight': 5, 'gamma': 1.6944897560192993, 'max_bin': 256, 'max_depth': 5}. Best is trial 15 with value: 0.6234464285714285.
[I 2026-04-22 13:49:40,562] Trial 21 finished with value: 0.6220793650793651 and parameters: {'learning_rate': 0.005648002952374807, 'n_estimators': 1353, 'reg_lambda': 0.6486195032163167, 'reg_alpha': 0.0010081969008937167, 'subsample': 0.7427492578944302, 'colsample_bytree': 0.8694643821834775, 'min_child_weight': 6, 'gamma': 1.3932934622896789, 'max_bin': 256, 'max_depth': 5}. Best is trial 15 with value: 0.6234464285714285.
[I 2026-04-22 13:50:14,350] Trial 22 finished with value: 0.6173948412698413 and parameters: {'learning_rate': 0.004066819907804895, 'n_estimators': 1350, 'reg_lambda': 1.1110591536415755, 'reg_alpha': 0.0006055394230358124, 'subsample': 0.7373197407863394, 'colsample_bytree': 0.8748461946968793, 'min_child_weight': 6, 'gamma': 1.5686869459526696, 'max_bin': 256, 'max_depth': 5}. Best is trial 15 with value: 0.6234464285714285.
[I 2026-04-22 13:50:33,897] Trial 23 finished with value: 0.6238452380952382 and parameters: {'learning_rate': 0.009196470420278192, 'n_estimators': 1162, 'reg_lambda': 0.6316481907935888, 'reg_alpha': 0.0058620054678203415, 'subsample': 0.8579198832089692, 'colsample_bytree': 0.8337466109008047, 'min_child_weight': 7, 'gamma': 0.5015544472158925, 'max_bin': 256, 'max_depth': 5}. Best is trial 23 with value: 0.6238452380952382.
[I 2026-04-22 13:50:50,581] Trial 24 finished with value: 0.6175952380952381 and parameters: {'learning_rate': 0.010649608744438073, 'n_estimators': 1105, 'reg_lambda': 1.4378095944644922, 'reg_alpha': 0.007604155727899021, 'subsample': 0.8400522869652309, 'colsample_bytree': 0.7561479653435691, 'min_child_weight': 7, 'gamma': 0.6306339793319085, 'max_bin': 256, 'max_depth': 4}. Best is trial 23 with value: 0.6238452380952382.
[I 2026-04-22 13:51:10,294] Trial 25 finished with value: 0.6226369047619049 and parameters: {'learning_rate': 0.009571539875073504, 'n_estimators': 1184, 'reg_lambda': 2.0027318616252825, 'reg_alpha': 0.011283790993188016, 'subsample': 0.8671292145748454, 'colsample_bytree': 0.8361996271156378, 'min_child_weight': 7, 'gamma': 0.4204151085108909, 'max_bin': 256, 'max_depth': 5}. Best is trial 23 with value: 0.6238452380952382.
[I 2026-04-22 13:51:32,934] Trial 26 finished with value: 0.615761904761905 and parameters: {'learning_rate': 0.006990670926758376, 'n_estimators': 1005, 'reg_lambda': 0.9377342101285852, 'reg_alpha': 0.003316813422892917, 'subsample': 0.782965357675061, 'colsample_bytree': 0.8152208471927865, 'min_child_weight': 5, 'gamma': 1.9684169614713816, 'max_bin': 256, 'max_depth': 5}. Best is trial 23 with value: 0.6238452380952382.
[I 2026-04-22 13:51:43,031] Trial 27 finished with value: 0.6075813492063493 and parameters: {'learning_rate': 0.03944862663989057, 'n_estimators': 919, 'reg_lambda': 3.3120454301088142, 'reg_alpha': 0.00022119004478142023, 'subsample': 0.8016459642300784, 'colsample_bytree': 0.7452280591945283, 'min_child_weight': 4, 'gamma': 3.0404422111433584, 'max_bin': 256, 'max_depth': 4}. Best is trial 23 with value: 0.6238452380952382.
[I 2026-04-22 13:51:58,981] Trial 28 finished with value: 0.6148234126984128 and parameters: {'learning_rate': 0.014648506150524014, 'n_estimators': 751, 'reg_lambda': 1.2878185524759251, 'reg_alpha': 0.2071425749761773, 'subsample': 0.8731791813714108, 'colsample_bytree': 0.9179017562448363, 'min_child_weight': 7, 'gamma': 0.47307124940201256, 'max_bin': 256, 'max_depth': 5}. Best is trial 23 with value: 0.6238452380952382.
[I 2026-04-22 13:52:27,894] Trial 29 finished with value: 0.6110734126984126 and parameters: {'learning_rate': 0.0037648431215226872, 'n_estimators': 1263, 'reg_lambda': 0.9113318929425025, 'reg_alpha': 0.0017523493240151704, 'subsample': 0.7246802832844744, 'colsample_bytree': 0.6844263269388721, 'min_child_weight': 8, 'gamma': 1.2012788573131288, 'max_bin': 128, 'max_depth': 6}. Best is trial 23 with value: 0.6238452380952382.

======================================================================
  BEST PARAMS
======================================================================
{'learning_rate': 0.009196470420278192, 'n_estimators': 1162, 'reg_lambda': 0.6316481907935888, 'reg_alpha': 0.0058620054678203415, 'subsample': 0.8579198832089692, 'colsample_bytree': 0.8337466109008047, 'min_child_weight': 7, 'gamma': 0.5015544472158925, 'max_bin': 256, 'max_depth': 5}
Best score: 0.6238
Final score: 0.6238
Calibration: alpha=0.525, score 0.6238 -> 0.6339, precision 0.5860 -> 0.5950, recall 0.6617 -> 0.6729
Targeted calibration labels: palette, borders, delta_V_top_bottom, delta_V_left_right, delta_V_center_periphery, structure_order, delta_H_center_periphery, elongation

Most under-selected labels after calibration:
  palette: true=0.027, selected=0.001, delta=-0.026, recall@10=0.042
  perimeter: true=0.050, selected=0.028, delta=-0.022, recall@10=0.409
  delta_S_center_periphery: true=0.035, selected=0.019, delta=-0.016, recall@10=0.161
  delta_V_top_bottom: true=0.032, selected=0.016, delta=-0.016, recall@10=0.250
  structure_order: true=0.017, selected=0.003, delta=-0.014, recall@10=0.133
  borders: true=0.031, selected=0.017, delta=-0.014, recall@10=0.296
  elongation: true=0.023, selected=0.012, delta=-0.011, recall@10=0.200
  fractal_dimension: true=0.043, selected=0.033, delta=-0.010, recall@10=0.421

Most over-selected labels after calibration:
  asymmetry: true=0.072, selected=0.100, delta=0.028, precision=0.630
  delta_V_inner_rim: true=0.069, selected=0.094, delta=0.025, precision=0.628
  color_homogeneity: true=0.077, selected=0.100, delta=0.023, precision=0.680
  contrast: true=0.056, selected=0.077, delta=0.021, precision=0.506
  dominant_hue: true=0.055, selected=0.073, delta=0.018, precision=0.562
  delta_S_left_right: true=0.047, selected=0.061, delta=0.014, precision=0.443
  std_H_lesion: true=0.030, selected=0.038, delta=0.008, precision=0.368
  color_distance_euclidean: true=0.095, selected=0.100, delta=0.005, precision=0.840
Checkpoint saved to: /kaggle/working/xgb_buckets.pkl

In [13]:
result = xgb(
    features_csv=FEATURES_CSV,
    annotations_csv=ANNOTATIONS_CSV,
    feature_set="selected_buckets",
    model_type="xgb_classifier_chain",
    n_trials=30,
    checkpoint_path="/kaggle/working/xgb_classifier_chain_importance.pkl",
    calibrate_label_bias=True,
    kwargs=optuna_kwargs,
)

======================================================================
  XGBoost importance model
======================================================================

[I 2026-04-22 13:52:50,145] A new study created in memory with name: no-name-12707c58-496e-4e00-84d4-895ff8689784
[I 2026-04-22 13:54:20,607] Trial 0 finished with value: 0.6169742063492063 and parameters: {'learning_rate': 0.006584767165456215, 'n_estimators': 629, 'reg_lambda': 1.401929929758677, 'reg_alpha': 0.010342100318265974, 'subsample': 0.782980120611096, 'colsample_bytree': 0.6313733115240806, 'min_child_weight': 5, 'gamma': 1.1886220250483637, 'max_bin': 512, 'max_depth': 6}. Best is trial 0 with value: 0.6169742063492063.
[I 2026-04-22 13:55:26,428] Trial 1 finished with value: 0.6121567460317461 and parameters: {'learning_rate': 0.012879988511717106, 'n_estimators': 740, 'reg_lambda': 2.4970643122197327, 'reg_alpha': 0.002709090327588364, 'subsample': 0.6210078431537303, 'colsample_bytree': 0.7007418197701788, 'min_child_weight': 7, 'gamma': 4.48955634449045, 'max_bin': 128, 'max_depth': 4}. Best is trial 0 with value: 0.6169742063492063.
[I 2026-04-22 13:57:04,387] Trial 2 finished with value: 0.6143789682539682 and parameters: {'learning_rate': 0.00525196341749699, 'n_estimators': 1090, 'reg_lambda': 2.5440696609657403, 'reg_alpha': 0.00012423871599349443, 'subsample': 0.8960852864263533, 'colsample_bytree': 0.7253015410481491, 'min_child_weight': 2, 'gamma': 4.498305017668175, 'max_bin': 256, 'max_depth': 4}. Best is trial 0 with value: 0.6169742063492063.
[I 2026-04-22 13:57:50,630] Trial 3 finished with value: 0.6202738095238096 and parameters: {'learning_rate': 0.03196163080920539, 'n_estimators': 905, 'reg_lambda': 3.21019123082132, 'reg_alpha': 0.004133571191781264, 'subsample': 0.6897416234427136, 'colsample_bytree': 0.8097268675357353, 'min_child_weight': 1, 'gamma': 0.9333162195337336, 'max_bin': 128, 'max_depth': 7}. Best is trial 3 with value: 0.6202738095238096.
[I 2026-04-22 13:59:09,974] Trial 4 finished with value: 0.6093214285714286 and parameters: {'learning_rate': 0.008913580594149323, 'n_estimators': 500, 'reg_lambda': 5.045175562254797, 'reg_alpha': 0.04443767849593424, 'subsample': 0.794931645404551, 'colsample_bytree': 0.5941660811427163, 'min_child_weight': 1, 'gamma': 4.148687021967788, 'max_bin': 128, 'max_depth': 5}. Best is trial 3 with value: 0.6202738095238096.
[I 2026-04-22 14:00:08,267] Trial 5 finished with value: 0.608845238095238 and parameters: {'learning_rate': 0.016437416437740146, 'n_estimators': 1058, 'reg_lambda': 2.0668607691132714, 'reg_alpha': 0.01229699941112452, 'subsample': 0.7710922579228509, 'colsample_bytree': 0.7418534086562578, 'min_child_weight': 6, 'gamma': 3.4461575879038815, 'max_bin': 512, 'max_depth': 4}. Best is trial 3 with value: 0.6202738095238096.
[I 2026-04-22 14:00:48,834] Trial 6 finished with value: 0.6205694444444445 and parameters: {'learning_rate': 0.04152049537757619, 'n_estimators': 1145, 'reg_lambda': 3.1341914913934685, 'reg_alpha': 0.00030889519735979436, 'subsample': 0.7681268563374717, 'colsample_bytree': 0.7437417659296764, 'min_child_weight': 5, 'gamma': 0.06493981910207447, 'max_bin': 128, 'max_depth': 4}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:01:32,528] Trial 7 finished with value: 0.6067321428571428 and parameters: {'learning_rate': 0.045040965373734525, 'n_estimators': 720, 'reg_lambda': 5.303378862991709, 'reg_alpha': 0.00782547668290296, 'subsample': 0.6295155016922194, 'colsample_bytree': 0.9270725063511303, 'min_child_weight': 5, 'gamma': 2.564507996338381, 'max_bin': 256, 'max_depth': 6}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:03:39,624] Trial 8 finished with value: 0.6144960317460317 and parameters: {'learning_rate': 0.0038331014471286026, 'n_estimators': 1477, 'reg_lambda': 0.7666699468262772, 'reg_alpha': 0.000978232150484151, 'subsample': 0.8629728039940188, 'colsample_bytree': 0.6059483700715722, 'min_child_weight': 6, 'gamma': 0.9885615081795757, 'max_bin': 512, 'max_depth': 5}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:04:15,048] Trial 9 finished with value: 0.6067876984126984 and parameters: {'learning_rate': 0.07397017761218935, 'n_estimators': 1229, 'reg_lambda': 4.886943908161483, 'reg_alpha': 0.0050781738732536075, 'subsample': 0.9460014046560611, 'colsample_bytree': 0.5530808037466882, 'min_child_weight': 1, 'gamma': 1.59380235205957, 'max_bin': 256, 'max_depth': 5}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:05:07,116] Trial 10 finished with value: 0.6004464285714286 and parameters: {'learning_rate': 0.025770483708203635, 'n_estimators': 1553, 'reg_lambda': 4.276755681619114, 'reg_alpha': 0.00010625538213341202, 'subsample': 0.7391877437151924, 'colsample_bytree': 0.863329617611914, 'min_child_weight': 3, 'gamma': 0.05268076988190991, 'max_bin': 128, 'max_depth': 7}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:05:54,417] Trial 11 finished with value: 0.6175793650793651 and parameters: {'learning_rate': 0.033927507817200955, 'n_estimators': 885, 'reg_lambda': 3.597295533177369, 'reg_alpha': 0.2413862784009719, 'subsample': 0.6951338599674565, 'colsample_bytree': 0.8216533997366418, 'min_child_weight': 3, 'gamma': 0.02503348665449945, 'max_bin': 128, 'max_depth': 7}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:06:31,697] Trial 12 finished with value: 0.5991071428571428 and parameters: {'learning_rate': 0.06411093140324425, 'n_estimators': 1275, 'reg_lambda': 3.466511809749809, 'reg_alpha': 0.0005976246190066811, 'subsample': 0.7136631081170447, 'colsample_bytree': 0.9994722143234709, 'min_child_weight': 8, 'gamma': 0.6554927379013745, 'max_bin': 128, 'max_depth': 6}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:07:25,394] Trial 13 finished with value: 0.6092738095238096 and parameters: {'learning_rate': 0.023896737345757594, 'n_estimators': 923, 'reg_lambda': 4.020846343422011, 'reg_alpha': 0.0006154737300148432, 'subsample': 0.6639630253879629, 'colsample_bytree': 0.8124382203935855, 'min_child_weight': 4, 'gamma': 1.97478797823985, 'max_bin': 128, 'max_depth': 7}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:08:07,703] Trial 14 finished with value: 0.6031150793650794 and parameters: {'learning_rate': 0.04212490549419152, 'n_estimators': 1298, 'reg_lambda': 5.987394850985855, 'reg_alpha': 0.03753684367827732, 'subsample': 0.85213571961087, 'colsample_bytree': 0.8973692453210911, 'min_child_weight': 4, 'gamma': 2.6532646073543393, 'max_bin': 128, 'max_depth': 5}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:09:04,075] Trial 15 finished with value: 0.6174107142857144 and parameters: {'learning_rate': 0.02029964352865845, 'n_estimators': 951, 'reg_lambda': 2.7811899582153483, 'reg_alpha': 0.0016305112553525603, 'subsample': 0.6781329748678558, 'colsample_bytree': 0.6689025247950027, 'min_child_weight': 3, 'gamma': 0.5874893494503809, 'max_bin': 128, 'max_depth': 6}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:09:43,009] Trial 16 finished with value: 0.6002678571428571 and parameters: {'learning_rate': 0.04924314598046795, 'n_estimators': 1157, 'reg_lambda': 1.8908327452254383, 'reg_alpha': 0.0002531434060158236, 'subsample': 0.8373994013437325, 'colsample_bytree': 0.7722905496456314, 'min_child_weight': 6, 'gamma': 1.8403229457449322, 'max_bin': 128, 'max_depth': 7}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:10:28,182] Trial 17 finished with value: 0.6058710317460317 and parameters: {'learning_rate': 0.03268105577499109, 'n_estimators': 1397, 'reg_lambda': 3.2091963970340056, 'reg_alpha': 0.0003289091671715732, 'subsample': 0.7357794563655938, 'colsample_bytree': 0.8030151538320801, 'min_child_weight': 2, 'gamma': 0.5702788449929719, 'max_bin': 128, 'max_depth': 4}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:11:33,999] Trial 18 finished with value: 0.6070952380952381 and parameters: {'learning_rate': 0.01135371862667688, 'n_estimators': 827, 'reg_lambda': 4.385019318931054, 'reg_alpha': 0.02480870847892697, 'subsample': 0.9814592796723456, 'colsample_bytree': 0.861608244901002, 'min_child_weight': 8, 'gamma': 3.1373566449746177, 'max_bin': 512, 'max_depth': 6}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:12:16,591] Trial 19 finished with value: 0.6153849206349207 and parameters: {'learning_rate': 0.05812601593954997, 'n_estimators': 986, 'reg_lambda': 3.2068792479536836, 'reg_alpha': 0.1849206137454622, 'subsample': 0.6471020836510777, 'colsample_bytree': 0.6824016599740518, 'min_child_weight': 2, 'gamma': 1.4333123446090816, 'max_bin': 256, 'max_depth': 5}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:13:03,590] Trial 20 finished with value: 0.6084761904761906 and parameters: {'learning_rate': 0.030272957168240352, 'n_estimators': 1136, 'reg_lambda': 1.2200377146670918, 'reg_alpha': 0.0030781946740721785, 'subsample': 0.7554722628514601, 'colsample_bytree': 0.9570052298190747, 'min_child_weight': 4, 'gamma': 2.1949024061595823, 'max_bin': 128, 'max_depth': 4}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:13:51,979] Trial 21 finished with value: 0.6082003968253968 and parameters: {'learning_rate': 0.03719737323093328, 'n_estimators': 851, 'reg_lambda': 3.791663379021515, 'reg_alpha': 0.2640510219779029, 'subsample': 0.6980825770632653, 'colsample_bytree': 0.8251656987069715, 'min_child_weight': 3, 'gamma': 0.15263070098954046, 'max_bin': 128, 'max_depth': 7}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:14:54,164] Trial 22 finished with value: 0.6150654761904762 and parameters: {'learning_rate': 0.017297327567178524, 'n_estimators': 1004, 'reg_lambda': 2.9727113650510844, 'reg_alpha': 0.020005260849190885, 'subsample': 0.6781637323644641, 'colsample_bytree': 0.7713593186518618, 'min_child_weight': 1, 'gamma': 0.11171508071484976, 'max_bin': 128, 'max_depth': 7}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:15:47,596] Trial 23 finished with value: 0.614109126984127 and parameters: {'learning_rate': 0.028593576561041743, 'n_estimators': 786, 'reg_lambda': 3.5884725975829044, 'reg_alpha': 0.056334867564759396, 'subsample': 0.8185655808009861, 'colsample_bytree': 0.8628077075611192, 'min_child_weight': 5, 'gamma': 0.8087411582957675, 'max_bin': 128, 'max_depth': 7}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:16:28,839] Trial 24 finished with value: 0.6033769841269842 and parameters: {'learning_rate': 0.05519916293957409, 'n_estimators': 885, 'reg_lambda': 2.1808349835802296, 'reg_alpha': 0.10026880220386848, 'subsample': 0.716722713879534, 'colsample_bytree': 0.7584699064935462, 'min_child_weight': 3, 'gamma': 0.41827420148041716, 'max_bin': 128, 'max_depth': 7}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:17:28,605] Trial 25 finished with value: 0.6098353174603175 and parameters: {'learning_rate': 0.02186881003119873, 'n_estimators': 657, 'reg_lambda': 4.258077325299464, 'reg_alpha': 0.11782513906676047, 'subsample': 0.6005638633857864, 'colsample_bytree': 0.8216789392973745, 'min_child_weight': 2, 'gamma': 1.1004368572153242, 'max_bin': 128, 'max_depth': 6}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:18:18,295] Trial 26 finished with value: 0.6107460317460318 and parameters: {'learning_rate': 0.0385959206883301, 'n_estimators': 1211, 'reg_lambda': 3.735901469486588, 'reg_alpha': 0.001561714134814749, 'subsample': 0.6993202400057671, 'colsample_bytree': 0.7140584539254123, 'min_child_weight': 4, 'gamma': 0.2562973735851535, 'max_bin': 128, 'max_depth': 7}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:18:59,579] Trial 27 finished with value: 0.6036567460317461 and parameters: {'learning_rate': 0.07629477092974969, 'n_estimators': 1355, 'reg_lambda': 2.8980077421769046, 'reg_alpha': 0.00024407961446188187, 'subsample': 0.7663037583181419, 'colsample_bytree': 0.7936916884225101, 'min_child_weight': 1, 'gamma': 0.015604350383018242, 'max_bin': 128, 'max_depth': 6}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:19:53,628] Trial 28 finished with value: 0.6087321428571429 and parameters: {'learning_rate': 0.034746955385167234, 'n_estimators': 1061, 'reg_lambda': 4.642500208938498, 'reg_alpha': 0.0061830714463873, 'subsample': 0.6544517304665773, 'colsample_bytree': 0.8506685987182416, 'min_child_weight': 7, 'gamma': 1.4057799637945492, 'max_bin': 512, 'max_depth': 7}. Best is trial 6 with value: 0.6205694444444445.
[I 2026-04-22 14:20:55,900] Trial 29 finished with value: 0.6158174603174604 and parameters: {'learning_rate': 0.019839546107971562, 'n_estimators': 565, 'reg_lambda': 1.6091723841286765, 'reg_alpha': 0.014544613561713965, 'subsample': 0.7968852016154242, 'colsample_bytree': 0.648260098049698, 'min_child_weight': 5, 'gamma': 1.033664037717914, 'max_bin': 256, 'max_depth': 6}. Best is trial 6 with value: 0.6205694444444445.

======================================================================
  BEST PARAMS
======================================================================
{'learning_rate': 0.04152049537757619, 'n_estimators': 1145, 'reg_lambda': 3.1341914913934685, 'reg_alpha': 0.00030889519735979436, 'subsample': 0.7681268563374717, 'colsample_bytree': 0.7437417659296764, 'min_child_weight': 5, 'gamma': 0.06493981910207447, 'max_bin': 128, 'max_depth': 4}
Best score: 0.6206
Final score: 0.6206
Calibration: alpha=0.250, score 0.6206 -> 0.6230, precision 0.5820 -> 0.5840, recall 0.6591 -> 0.6621
Targeted calibration labels: palette, borders, delta_V_top_bottom, delta_V_left_right, delta_V_center_periphery, structure_order, delta_H_center_periphery, elongation

Most under-selected labels after calibration:
  delta_V_top_bottom: true=0.032, selected=0.009, delta=-0.023, recall@10=0.143
  palette: true=0.027, selected=0.005, delta=-0.022, recall@10=0.042
  perimeter: true=0.050, selected=0.032, delta=-0.018, recall@10=0.386
  borders: true=0.031, selected=0.014, delta=-0.017, recall@10=0.296
  elongation: true=0.023, selected=0.010, delta=-0.013, recall@10=0.050
  fractal_dimension: true=0.043, selected=0.032, delta=-0.011, recall@10=0.421
  delta_V_left_right: true=0.016, selected=0.005, delta=-0.011, recall@10=0.143
  structure_order: true=0.017, selected=0.007, delta=-0.010, recall@10=0.200

Most over-selected labels after calibration:
  asymmetry: true=0.072, selected=0.098, delta=0.026, precision=0.622
  delta_V_inner_rim: true=0.069, selected=0.092, delta=0.023, precision=0.630
  color_homogeneity: true=0.077, selected=0.098, delta=0.021, precision=0.684
  contrast: true=0.056, selected=0.072, delta=0.016, precision=0.542
  dominant_hue: true=0.055, selected=0.070, delta=0.015, precision=0.543
  std_H_lesion: true=0.030, selected=0.042, delta=0.012, precision=0.310
  delta_S_left_right: true=0.047, selected=0.056, delta=0.009, precision=0.429
  eccentricity: true=0.036, selected=0.044, delta=0.008, precision=0.432
Checkpoint saved to: /kaggle/working/xgb_classifier_chain_importance.pkl

#### 3.1.2 MLP

In [16]:
mlp_kwargs = {
    "batch_size": {"type": "categorical", "choices": [16, 32, 64]},
    "learning_rate": {"type": "float", "low": 1e-4, "high": 3e-3, "log": True},
    "weight_decay": {"type": "float", "low": 1e-6, "high": 5e-3, "log": True},
    "dropout": {"type": "float", "low": 0.1, "high": 0.5},
    "max_epochs": {"type": "int", "low": 40, "high": 100},
    "patience": {"type": "int", "low": 8, "high": 20},
    "hidden1": {"type": "categorical", "choices": [64, 128, 192, 256]},
    "hidden2": {"type": "categorical", "choices": [32, 64, 96, 128]},
}

result = mlp(
    features_csv=FEATURES_CSV,
    annotations_csv=ANNOTATIONS_CSV,
    feature_set="numeric_only",
    n_trials=50,
    n_splits=5,
    checkpoint_path="/kaggle/working/mlp_importance.pt",
    kwargs=mlp_kwargs,
)

[I 2026-04-22 14:22:08,478] A new study created in memory with name: no-name-cfc7d398-2b72-4003-849e-96e81a95ac08
[I 2026-04-22 14:22:18,729] Trial 0 finished with value: 0.5115813492063491 and parameters: {'batch_size': 32, 'learning_rate': 0.001253829250364845, 'weight_decay': 6.069655108855242e-06, 'dropout': 0.329282646189211, 'max_epochs': 83, 'patience': 11, 'hidden1': 64, 'hidden2': 64}. Best is trial 0 with value: 0.5115813492063491.
[I 2026-04-22 14:22:36,735] Trial 1 finished with value: 0.5096039682539683 and parameters: {'batch_size': 16, 'learning_rate': 0.0012933901465471973, 'weight_decay': 0.0036656639812927376, 'dropout': 0.3603767576014817, 'max_epochs': 54, 'patience': 18, 'hidden1': 192, 'hidden2': 96}. Best is trial 0 with value: 0.5115813492063491.
[I 2026-04-22 14:22:50,321] Trial 2 finished with value: 0.5041626984126983 and parameters: {'batch_size': 16, 'learning_rate': 0.00025462224819268817, 'weight_decay': 0.00027124626265539033, 'dropout': 0.13046542405624215, 'max_epochs': 48, 'patience': 11, 'hidden1': 128, 'hidden2': 128}. Best is trial 0 with value: 0.5115813492063491.
[I 2026-04-22 14:23:08,873] Trial 3 finished with value: 0.5203238095238095 and parameters: {'batch_size': 16, 'learning_rate': 0.0012575153906303218, 'weight_decay': 9.055107967619005e-06, 'dropout': 0.12382774340306933, 'max_epochs': 96, 'patience': 17, 'hidden1': 128, 'hidden2': 32}. Best is trial 3 with value: 0.5203238095238095.
[I 2026-04-22 14:23:18,317] Trial 4 finished with value: 0.5029706349206349 and parameters: {'batch_size': 32, 'learning_rate': 0.0008586776951666771, 'weight_decay': 2.6971898658726047e-05, 'dropout': 0.1777213725855188, 'max_epochs': 62, 'patience': 20, 'hidden1': 64, 'hidden2': 96}. Best is trial 3 with value: 0.5203238095238095.
[I 2026-04-22 14:23:20,329] Trial 5 pruned.
[I 2026-04-22 14:23:26,401] Trial 6 pruned.
[I 2026-04-22 14:23:27,968] Trial 7 pruned.
[I 2026-04-22 14:23:33,094] Trial 8 pruned.
[I 2026-04-22 14:23:39,577] Trial 9 pruned.
[I 2026-04-22 14:23:41,898] Trial 10 pruned.
[I 2026-04-22 14:23:43,993] Trial 11 pruned.
[I 2026-04-22 14:23:45,856] Trial 12 pruned.
[I 2026-04-22 14:23:49,626] Trial 13 pruned.
[I 2026-04-22 14:23:51,674] Trial 14 pruned.
[I 2026-04-22 14:23:57,069] Trial 15 pruned.
[I 2026-04-22 14:23:59,735] Trial 16 pruned.
[I 2026-04-22 14:24:03,772] Trial 17 pruned.
[I 2026-04-22 14:24:07,312] Trial 18 pruned.
[I 2026-04-22 14:24:08,515] Trial 19 pruned.
[I 2026-04-22 14:24:22,160] Trial 20 pruned.
[I 2026-04-22 14:24:38,600] Trial 21 finished with value: 0.5098003968253968 and parameters: {'batch_size': 16, 'learning_rate': 0.001025347616274765, 'weight_decay': 0.00017028425024141655, 'dropout': 0.3660609896769618, 'max_epochs': 54, 'patience': 18, 'hidden1': 192, 'hidden2': 96}. Best is trial 3 with value: 0.5203238095238095.
[I 2026-04-22 14:24:43,753] Trial 22 pruned.
[I 2026-04-22 14:24:48,223] Trial 23 pruned.
[I 2026-04-22 14:25:04,545] Trial 24 finished with value: 0.5155123015873015 and parameters: {'batch_size': 16, 'learning_rate': 0.001628169443227092, 'weight_decay': 0.0002973553398627106, 'dropout': 0.3281877778417263, 'max_epochs': 81, 'patience': 19, 'hidden1': 128, 'hidden2': 96}. Best is trial 3 with value: 0.5203238095238095.
[I 2026-04-22 14:25:09,977] Trial 25 pruned.
[I 2026-04-22 14:25:35,970] Trial 26 finished with value: 0.5180206349206349 and parameters: {'batch_size': 16, 'learning_rate': 0.0024337449390605284, 'weight_decay': 2.1570234475965038e-06, 'dropout': 0.17446063590546468, 'max_epochs': 78, 'patience': 19, 'hidden1': 128, 'hidden2': 64}. Best is trial 3 with value: 0.5203238095238095.
[I 2026-04-22 14:25:54,806] Trial 27 finished with value: 0.5252476190476191 and parameters: {'batch_size': 16, 'learning_rate': 0.0022820459009915742, 'weight_decay': 2.04662443543063e-06, 'dropout': 0.17793534095022662, 'max_epochs': 76, 'patience': 19, 'hidden1': 128, 'hidden2': 128}. Best is trial 27 with value: 0.5252476190476191.
[I 2026-04-22 14:26:10,203] Trial 28 finished with value: 0.5293666666666667 and parameters: {'batch_size': 16, 'learning_rate': 0.0024498724278737565, 'weight_decay': 2.0739704029626893e-06, 'dropout': 0.16763255787743894, 'max_epochs': 74, 'patience': 19, 'hidden1': 128, 'hidden2': 128}. Best is trial 28 with value: 0.5293666666666667.
[I 2026-04-22 14:26:27,839] Trial 29 finished with value: 0.5223472222222222 and parameters: {'batch_size': 16, 'learning_rate': 0.0022003506783957543, 'weight_decay': 9.945598607541703e-06, 'dropout': 0.14578533065763793, 'max_epochs': 68, 'patience': 16, 'hidden1': 128, 'hidden2': 128}. Best is trial 28 with value: 0.5293666666666667.
[I 2026-04-22 14:26:43,029] Trial 30 finished with value: 0.5255313492063494 and parameters: {'batch_size': 16, 'learning_rate': 0.0022853033042027114, 'weight_decay': 3.833497618289312e-06, 'dropout': 0.14736658706211342, 'max_epochs': 67, 'patience': 16, 'hidden1': 128, 'hidden2': 128}. Best is trial 28 with value: 0.5293666666666667.
[I 2026-04-22 14:26:57,569] Trial 31 finished with value: 0.5279972222222222 and parameters: {'batch_size': 16, 'learning_rate': 0.002268761747003073, 'weight_decay': 3.990107906862274e-06, 'dropout': 0.14978902792182716, 'max_epochs': 67, 'patience': 16, 'hidden1': 128, 'hidden2': 128}. Best is trial 28 with value: 0.5293666666666667.
[I 2026-04-22 14:27:13,377] Trial 32 finished with value: 0.5197730158730158 and parameters: {'batch_size': 16, 'learning_rate': 0.002932199454834238, 'weight_decay': 3.7821297882663646e-06, 'dropout': 0.1972046940300096, 'max_epochs': 63, 'patience': 16, 'hidden1': 128, 'hidden2': 128}. Best is trial 28 with value: 0.5293666666666667.
[I 2026-04-22 14:27:31,195] Trial 33 finished with value: 0.5249047619047619 and parameters: {'batch_size': 16, 'learning_rate': 0.0022787537986202378, 'weight_decay': 1.868730568795405e-06, 'dropout': 0.10152600446109161, 'max_epochs': 74, 'patience': 18, 'hidden1': 128, 'hidden2': 128}. Best is trial 28 with value: 0.5293666666666667.
[I 2026-04-22 14:27:37,426] Trial 34 pruned.
[I 2026-04-22 14:27:56,885] Trial 35 finished with value: 0.5278519841269841 and parameters: {'batch_size': 16, 'learning_rate': 0.002228329468289239, 'weight_decay': 1.7453934637871678e-06, 'dropout': 0.19230714196447252, 'max_epochs': 67, 'patience': 19, 'hidden1': 128, 'hidden2': 128}. Best is trial 28 with value: 0.5293666666666667.
[I 2026-04-22 14:28:11,058] Trial 36 finished with value: 0.5324972222222222 and parameters: {'batch_size': 16, 'learning_rate': 0.001940459759750493, 'weight_decay': 1.0059662006969984e-06, 'dropout': 0.13281780165796125, 'max_epochs': 65, 'patience': 16, 'hidden1': 128, 'hidden2': 128}. Best is trial 36 with value: 0.5324972222222222.
[I 2026-04-22 14:28:18,594] Trial 37 pruned.
[I 2026-04-22 14:28:20,331] Trial 38 pruned.
[I 2026-04-22 14:28:37,371] Trial 39 finished with value: 0.5230559523809524 and parameters: {'batch_size': 16, 'learning_rate': 0.001352218413146652, 'weight_decay': 2.4534774910945595e-06, 'dropout': 0.19862855119709844, 'max_epochs': 71, 'patience': 20, 'hidden1': 256, 'hidden2': 128}. Best is trial 36 with value: 0.5324972222222222.
[I 2026-04-22 14:28:44,166] Trial 40 pruned.
[I 2026-04-22 14:28:59,854] Trial 41 finished with value: 0.528227380952381 and parameters: {'batch_size': 16, 'learning_rate': 0.002617534464982069, 'weight_decay': 4.275864828928776e-06, 'dropout': 0.14972482389280975, 'max_epochs': 67, 'patience': 16, 'hidden1': 128, 'hidden2': 128}. Best is trial 36 with value: 0.5324972222222222.
[I 2026-04-22 14:29:12,147] Trial 42 finished with value: 0.5304527777777778 and parameters: {'batch_size': 16, 'learning_rate': 0.0026890120496170975, 'weight_decay': 4.6583032630122375e-06, 'dropout': 0.14084427600719526, 'max_epochs': 70, 'patience': 13, 'hidden1': 128, 'hidden2': 128}. Best is trial 36 with value: 0.5324972222222222.
[I 2026-04-22 14:29:17,554] Trial 43 pruned.
[I 2026-04-22 14:29:30,975] Trial 44 finished with value: 0.5271119047619047 and parameters: {'batch_size': 16, 'learning_rate': 0.002575454351087491, 'weight_decay': 4.970844347858596e-06, 'dropout': 0.11333211344463934, 'max_epochs': 61, 'patience': 13, 'hidden1': 128, 'hidden2': 128}. Best is trial 36 with value: 0.5324972222222222.
[I 2026-04-22 14:29:48,646] Trial 45 finished with value: 0.5234249999999999 and parameters: {'batch_size': 16, 'learning_rate': 0.0019512952524899723, 'weight_decay': 2.855344657813606e-06, 'dropout': 0.15955141187249425, 'max_epochs': 54, 'patience': 14, 'hidden1': 128, 'hidden2': 128}. Best is trial 36 with value: 0.5324972222222222.
[I 2026-04-22 14:29:50,401] Trial 46 pruned.
[I 2026-04-22 14:29:56,380] Trial 47 pruned.
[I 2026-04-22 14:30:00,309] Trial 48 pruned.
[I 2026-04-22 14:30:09,441] Trial 49 pruned.

Best score: 0.5325
Best params: {'batch_size': 16, 'learning_rate': 0.001940459759750493, 'weight_decay': 1.0059662006969984e-06, 'dropout': 0.13281780165796125, 'max_epochs': 65, 'patience': 16, 'hidden1': 128, 'hidden2': 128}

Top trials:
 number    value             datetime_start          datetime_complete               duration  params_batch_size  params_dropout  params_hidden1  params_hidden2  params_learning_rate  params_max_epochs  params_patience  params_weight_decay    state
     36 0.532497 2026-04-22 14:27:56.886607 2026-04-22 14:28:11.058150 0 days 00:00:14.171543                 16        0.132818             128             128              0.001940                 65               16             0.000001 COMPLETE
     42 0.530453 2026-04-22 14:28:59.855340 2026-04-22 14:29:12.147163 0 days 00:00:12.291823                 16        0.140844             128             128              0.002689                 70               13             0.000005 COMPLETE
     28 0.529367 2026-04-22 14:25:54.807321 2026-04-22 14:26:10.203452 0 days 00:00:15.396131                 16        0.167633             128             128              0.002450                 74               19             0.000002 COMPLETE
     41 0.528227 2026-04-22 14:28:44.167650 2026-04-22 14:28:59.854277 0 days 00:00:15.686627                 16        0.149725             128             128              0.002618                 67               16             0.000004 COMPLETE
     31 0.527997 2026-04-22 14:26:43.030516 2026-04-22 14:26:57.569323 0 days 00:00:14.538807                 16        0.149789             128             128              0.002269                 67               16             0.000004 COMPLETE
     35 0.527852 2026-04-22 14:27:37.427141 2026-04-22 14:27:56.885181 0 days 00:00:19.458040                 16        0.192307             128             128              0.002228                 67               19             0.000002 COMPLETE
     44 0.527112 2026-04-22 14:29:17.555576 2026-04-22 14:29:30.975431 0 days 00:00:13.419855                 16        0.113332             128             128              0.002575                 61               13             0.000005 COMPLETE
     30 0.525531 2026-04-22 14:26:27.840913 2026-04-22 14:26:43.029280 0 days 00:00:15.188367                 16        0.147367             128             128              0.002285                 67               16             0.000004 COMPLETE
     27 0.525248 2026-04-22 14:25:35.971095 2026-04-22 14:25:54.806035 0 days 00:00:18.834940                 16        0.177935             128             128              0.002282                 76               19             0.000002 COMPLETE
     33 0.524905 2026-04-22 14:27:13.378298 2026-04-22 14:27:31.195882 0 days 00:00:17.817584                 16        0.101526             128             128              0.002279                 74               18             0.000002 COMPLETE

Final checkpoint saved to: /kaggle/working/mlp_importance.pt
Final score on full data reference: 0.8476

In [17]:
result = mlp_run(
    features_csv=FEATURES_CSV,
    annotations_csv=ANNOTATIONS_CSV,
    checkpoint_path="/kaggle/working/mlp_importance.pt",
    feature_set="numeric_only",
    skip_cv=True,
    max_epochs=100,
    kwargs={
        "batch_size": 32,
        "patience": 15,
        "learning_rate": 1e-3,
        "weight_decay": 1e-4,
        "dropout": 0.3,
        "hidden_dims_override": (128, 64),
    },
)

======================================================================
  MLP importance model
======================================================================

Best validation score: 0.5015
Checkpoint saved to: /kaggle/working/mlp_importance.pt

In [23]:
df = pd.read_csv(FEATURES_CSV)
result = rank_features_batch_mlp(
    df.head(10),
    importance_model_path="/kaggle/working/mlp_importance.pt",
    k=10,
    verbose=True,
)

result[["image_path", "important_labels"]].head()

In [13]:
df = pd.read_csv(FEATURES_CSV)
result = rank_features_batch(
    df,
    importance_model_path="/kaggle/working/xgb_importance.pkl",
    k=10,
    verbose=True,
)

result[["image_path", "important_labels"]].head()

100%|██████████| 4137/4137 [00:00<00:00, 8302.06it/s]

        image_path                                   important_labels
0   images/100.jpg  [shape:округлая, color_distance_euclidean:силь...
1  images/1000.jpg  [shape:овальная, color_distance_euclidean:умер...
2  images/1001.jpg  [shape:овальная, color_distance_euclidean:умер...
3  images/1002.jpg  [shape:овальная, color_distance_euclidean:выра...
4  images/1003.jpg  [shape:овальная, asymmetry:умеренная, color_di...

In [11]:
from model.model import load_checkpoint
import pandas as pd

checkpoint = load_checkpoint("/kaggle/working/xgb_importance.pkl")

report = pd.DataFrame(checkpoint["calibration_metadata"]["calibrated_report"])
report.sort_values("share_delta")

,label,positives,selected,hits,true_share,selected_share,share_delta,recall_at_k,precision_when_selected
20,delta_V_top_bottom,28,4,2,0.030973,0.004,-0.026973,0.071429,0.500000
3,palette,24,0,0,0.026549,0.000,-0.026549,0.000000,0.000000
1,borders,27,4,1,0.029867,0.004,-0.025867,0.037037,0.250000
15,delta_H_center_periphery,29,14,7,0.032080,0.014,-0.018080,0.241379,0.500000
19,delta_V_left_right,14,0,0,0.015487,0.000,-0.015487,0.000000,0.000000
17,delta_V_center_periphery,18,5,2,0.019912,0.005,-0.014912,0.111111,0.400000
23,glcm_energy,13,0,0,0.014381,0.000,-0.014381,0.000000,0.000000
11,perimeter,44,36,23,0.048673,0.036,-0.012673,0.522727,0.638889
4,texture,11,0,0,0.012168,0.000,-0.012168,0.000000,0.000000
10,structure_order,15,6,2,0.016593,0.006,-0.010593,0.133333,0.333333
5,elongation,20,16,4,0.022124,0.016,-0.006124,0.200000,0.250000
6,rim,34,34,14,0.037611,0.034,-0.003611,0.411765,0.411765
12,fractal_dimension,38,39,19,0.042035,0.039,-0.003035,0.500000,0.487179
16,delta_S_center_periphery,31,33,12,0.034292,0.033,-0.001292,0.387097,0.363636
8,shape,86,100,86,0.095133,0.100,0.004867,1.000000,0.860000
13,eccentricity,32,41,18,0.035398,0.041,0.005602,0.562500,0.439024
14,color_distance_euclidean,84,100,84,0.092920,0.100,0.007080,1.000000,0.840000
22,std_H_lesion,26,42,14,0.028761,0.042,0.013239,0.538462,0.333333
21,delta_S_left_right,41,62,25,0.045354,0.062,0.016646,0.609756,0.403226
7,color_homogeneity,68,100,68,0.075221,0.100,0.024779,1.000000,0.680000
9,dominant_hue,48,82,42,0.053097,0.082,0.028903,0.875000,0.512195
18,delta_V_inner_rim,61,97,60,0.067478,0.097,0.029522,0.983607,0.618557
0,asymmetry,63,100,63,0.069690,0.100,0.030310,1.000000,0.630000
2,contrast,49,85,42,0.054204,0.085,0.030796,0.857143,0.494118

## Шаг 4. Генерация клинического описания (Qwen2.5-7B)

In [ ]:
df = generate_descriptions_batch(df, device=device)
print("\nПример сгенерированного описания:")
print(df["description"].iloc[0])
# Сохранение результатов
output_csv = "features_with_descriptions.csv"
df.to_csv(output_csv, index=False)
print(f"\nСохранено: {len(df)} строк в {output_csv}")